#!/bin/bash
cd $web_path


case $action in
    --app-react-app | --app-react-project)
        cmd="create-${action[@]:6}"
        for name in $params
        do
            [[ $(is_dir "$web_path/$name") && $(confirm "¿Deseas eliminar $name?" Y) ]] && delete "$web_path/$name"
            npx $cmd $web_path/$name
        done
    ;;
    --app-laravel)
        for name in $params
        do
            [[ $(is_dir "$web_path/$name") && $(confirm "¿Deseas eliminar $name?" Y) ]] && delete "$web_path/$name"
            composer create-project --prefer-dist laravel/laravel $web_path/$name
        done
    ;;
esac