#!/bin/bash
cd $base_path


case $action in
    --server-upgrade)
        rm -rf $temp_path
        [[ -d "www" ]] && mv www $web_path
        [[ ! -d $amazon_path ]] && mkdir $amazon_path
        [[ ! -d $php_path ]] && mkdir $php_path
        [[ ! -d $resources_path ]] && mkdir $resources_path
        [[ ! -d $script_path ]] && mkdir $script_path
        [[ ! -d $views_path ]] && mkdir $views_path
        [[ ! -d $web_path ]] && mkdir $web_path
        [[ ! -d $temp_path ]] && mkdir $temp_path


        current_version=$server_version
        echo "Buscando actualizaciones..."
        wget -qO $temp_path/about https://raw.githubusercontent.com/$server_git/master/.env
        eval $(cat $temp_path/about | grep "server_version=")
        if [[ $current_version < $server_version ]]; then
            echo "Nueva versión [$current_version < $server_version]"
            if [[ $(confirm "¿Deseas descargarla?" N) ]]; then
                echo "Descargando..."
                wget -qO $temp_path/server.zip https://github.com/$server_git/archive/master.zip
                unzip -qq $temp_path/server.zip -d $temp_path
                # rsync $temp_path/$server_name-master/ $base_path
            fi
        else
            echo "El servidor está actualizado [$current_version]"
        fi

        # rm -rf $temp_path
    ;;

    # --server-install)
        # if [[ -z $(which php) ]]; then
            # sudo $base_path"/shell/apt-update"
        # fi
        # if [[ -z $(which composer) ]]; then
            # sudo $base_path"/shell/dist/composer"
        # fi
        # if [[ -z $(which node) ]]; then
            # sudo $base_path"/shell/dist/nodejs"
        # fi
    # ;;
esac
