#!/bin/bash
cd $base_path

case $action in
    --server-upgrade)
        echo 'Buscando actualizaciones...'
        wget -O $temp_path/version https://raw.githubusercontent.com/$server_git/master/.env -q
        nversion=$(cat $temp_path/version | grep server_version=)
        nversion="${nversion[@]:$(echo `expr index "$nversion" =`)}"
        if [[ -z $nversion ]]; then
            if [[ $(confirm "¿Reintentar descarga?" Y) ]]; then
                source $views_path/server
            else
                echo "El servidor no se actualizara"
            fi
        elif (( $(echo "$server_version < $nversion" | bc -l) )); then
            echo "Nueva versión [$server_version a $nversion]"
            if [[ $(confirm "¿Deseas descargarla?" Y) ]]; then
                wget -O $temp_path/server.zip https://github.com/$server_git/archive/master.zip
                unzip -qq $temp_path/server.zip -d $temp_path/
                merge_dir $temp_path/$server_name-master/ $base_path
            fi
        elif (( $(echo "$server_version >= $nversion" | bc -l) )); then
            echo "El servidor está actualizado [$server_version]"
        fi
        action="--server-install"
        source $views_path/server
    ;;
    --server-install)
        if [[ ! $(which php) || ! $(which mysql) ]]; then
            if ! grep -q "^deb .*ondrej/php" /etc/apt/sources.list /etc/apt/sources.list.d/*; then
                sudo add-apt-repository ppa:ondrej/php -y
            fi
            sudo apt-get install -y software-properties-common git apache2 mysql-server php7.4 php-pear php7.4-curl php7.4-dev php7.4-gd php7.4-mbstring php7.4-zip php7.4-mysql php7.4-xml
            sudo apt-get upgrade -y
            sudo mkdir -p /etc/apache2/logs/
            quiet sudo a2enmod rewrite
            quiet systemctl restart apache2
        fi
        if [[ ! $(which arc) ]]; then
            bash_arc="/etc/bash_completion.d/arcaela"
            [[ ! -f $bash_arc ]] && $(sudo touch $bash_arc && sudo chmod -R 777 $bash_arc)
            sudo echo "alias arc='$base_path/arc'" >> $bash_arc
        fi
        for pkg in $(scandir $script_path); do
            script $pkg
        done
        for bin_cmd in $(scandir $bin_path); do
            delete "/usr/bin/$bin_cmd"
            link $(realpath $bin_path/$bin_cmd) "/usr/bin/$bin_cmd"
            echo $(whereis $bin_cmd)
        done
    ;;
    --server-uninstall)
        delete /etc/bash_completion.d/arcaela
        delete /etc/bash_completion.d/arcaela*
    ;;
esac
