#!/bin/bash
isnpx=$(which npx)
apps="$params"

if [[ $isnpx || $(confirm "NodeJS es requerido, ¿Instalar ahora?" Y) ]]; then
    [[ -z $isnpx ]] && params="nodejs" && source $script_path/install
    if [[ $command == '--app-express' ]]; then
        [[ ! $(which express) ]] && echo "Error: npm i express-generator -g" && exit
        cmdline="express"
    fi
    if [[ $command == '--app-react' ]]; then
        [[ ! $(which npx) ]] && echo "Error: arc --install node" && exit
        cmdline="npx create-react-app"
    fi
    if [[ $command == '--app-laravel' ]]; then
        [[ ! $(which npx) ]] && echo "Error: arc --install composer" && exit
        cmdline="composer create-project --prefer-dist laravel/laravel"
    fi
    for name in $apps
    do
        if [[ ! -d $web_path/$name || $(confirm "¿Deseas eliminar $name?" Y) ]]; then
            $(delete "$web_path/$name")
            $cmdline $(path_go $web_path/$name)
        fi
    done
fi