#!/bin/bash


[[ $(which composer) ]] && echo "composer: Installed" || echo "composer: ---"
[[ -d "/etc/apache2/" ]] && echo "apache2: Installed" || echo "apache2: ---"
[[ $(which node) ]] && echo "node: Installed" || echo "node: ---"
[[ $(which npm) ]] && echo "npm: Installed" || echo "npm: ---"
[[ $(which npx) ]] && echo "npx: Installed" || echo "npx: ---"
[[ $(which php) ]] && echo "php: Installed" || echo "php: ---"
[[ $(which git) ]] && echo "git: Installed" || echo "git: ---"