#!/bin/bash
# Instalación de Composer
composer_path="$package_path/composer"
composer_executor="$package_path/composer/composer.phar"
composer_bash="/etc/bash_completion.d/arcaela_composer"
if [[ $action == 'remove-composer' ]]; then
    delete $composer_bash
    delete "$bin_path/composer"
else
    [[ -f $composer_bash ]] && source $composer_bash || $(sudo touch $composer_bash && sudo chmod -R 777 $composer_bash)
    [[ ! -d "$composer_path" ]] && mkdir -m 777 -p $composer_path
    [[ -z $(cat $composer_bash | grep 'export PATH=\$PATH\:'$composer_path) ]] && sudo echo 'export PATH=$PATH:'"$composer_path/vendor/bin" >> $composer_bash
    [[ -z $COMPOSER_HOME ]] && COMPOSER_HOME="$composer_path"           && sudo echo "export COMPOSER_HOME=$COMPOSER_HOME" >> $composer_bash
    [[ -z $CGR_BASE_DIR ]]  && CGR_BASE_DIR="$composer_path/global"     && sudo echo "export CGR_BASE_DIR=$CGR_BASE_DIR" >> $composer_bash
    [[ -z $CGR_BIN_DIR ]]   && CGR_BIN_DIR="$composer_path/vendor/bin"  && sudo echo "export CGR_BIN_DIR=$CGR_BIN_DIR" >> $composer_bash
    if [[ -f "$composer_executor" ]]; then
        sudo rm -rf "$bin_path/composer"
        link $composer_executor $bin_path/composer
    else
        [[ ! -f $temp_path/composer.php ]] && wget -O $temp_path/composer.php https://getcomposer.org/installer -q --show-progress
        echo "Instalando..."
        quiet php $temp_path/composer.php --install-dir=$composer_path/ --filename=composer.phar
        if [[ -f "$composer_executor" ]]; then
            sudo rm -rf "$bin_path/composer"
            link $composer_executor $bin_path/composer
        else
            echo "Error: No logramos instalar composer"
        fi
    fi
    sudo chmod -R 777 $composer_path
fi
# Fin de Composer