#!/bin/bash
source /etc/bashrc

composer_bin="/usr/local/bin/composer"
composer_home="$bin_path/composer"
mkdir -p $composer_home
sudo chmod -R 777 $composer_home
if [[ -z $COMPOSER_HOME ]]; then
    sudo echo "export COMPOSER_HOME=$composer_home/" >> /etc/bashrc
    sudo echo "export CGR_BASE_DIR=$composer_home/global" >> /etc/bashrc
    sudo echo "export CGR_BIN_DIR=$composer_home/vendor/bin" >> /etc/bashrc
    sudo echo "export CGR_BIN_DIR=$composer_home/vendor/bin" >> /etc/bashrc
    sudo echo 'export PATH=$PATH:'"$composer_home/vendor/bin" >> /etc/bashrc
    export COMPOSER_HOME="$composer_home/"
    export CGR_BASE_DIR="$composer_home/global"
    export CGR_BIN_DIR="$composer_home/vendor/bin"
fi

if [[ ! $(which composer) && $(confirm "¿Instalar composer?" Y) ]]; then
    echo "Descargando..."
    download -O $temp_path/composer.php https://getcomposer.org/installer
    echo "Instalando..."
    quiet php $temp_path/composer.php --install-dir=$composer_home/ --filename=composer.phar
    if [[ -f "$composer_home/composer.phar" ]]; then
        delete $composer_bin
        link "$composer_home/composer.phar" $composer_bin
        echo "$composer_bin -> $composer_home/composer.phar"
    else
        echo "Error: No logramos instalar composer"
    fi
fi
if [[ $(which composer) && ! $(exist $composer_home/vendor/bin/laravel) ]]; then
    echo "## Laravel"
    sudo chmod -R 777 $composer_home
    composer global require laravel/installer
fi