#!/bin/bash
composer_bin="/usr/local/bin/composer"
composer_home="$bin_path/composer"
mkdir -p $composer_home
sudo chmod -R $composer_home

if [[ ! $(which composer) && $(confirm "¿Instalar composer?" Y) ]]; then
    echo "Descargando..."
    download -O $temp_path/composer.php https://getcomposer.org/installer
    echo "Instalando..."
    export CGR_BASE_DIR="$composer_home/global"
    export CGR_BIN_DIR="$composer_home/vendor/bin"
    quiet php $temp_path/composer.php --install-dir=$composer_home/ --filename=composer.phar
    if [[ -f "$composer_home/composer.phar" ]]; then
        delete $composer_bin
        link "$composer_home/composer.phar" $composer_bin
        echo "$composer_bin -> $composer_home/composer.phar"
        sudo echo "export COMPOSER_HOME=$composer_home/" >> /etc/bash_completion
        sudo echo "export CGR_BASE_DIR=$composer_home/global" >> /etc/bash_completion
        sudo echo "export CGR_BIN_DIR=$composer_home/vendor/bin" >> /etc/bash_completion
        sudo echo "export CGR_BIN_DIR=$composer_home/vendor/bin" >> /etc/bash_completion
        sudo echo 'export PATH=$PATH:'"$composer_home/vendor/bin" >> /etc/bash_completion
    else
        echo "Error: No logramos instalar composer"
    fi
fi
if [[ $(which composer) && ! $(exist $composer_home/vendor/bin/laravel) ]]; then
    echo "## Laravel"
    export COMPOSER_HOME=$composer_home/
    export CGR_BASE_DIR=$composer_home/global
    export CGR_BIN_DIR=$composer_home/vendor/bin
    composer global require laravel/installer
fi