#!/bin/bash
root="$services_path/electrum"
sources="$root/ubuntu"
data="$root/data"
action="$command"
[[ ! -z $alter_cmd ]] && action="$alter_cmd"

function run_electrum {
    $sources/run_electrum $@ -D "$data"
}



case "$action" in
    --install)
        [[ $(which electrum) ]] && return
        $(rmkdir $root)
        echo "Registrando paquetes..."
        sudo apt-get install python3-pyqt5 libsecp256k1-0 python3-cryptography python-requests gettext -y
        _tt=$(pwd)
        cd $root/
        echo "Descargando Electrum..."
        git clone git://github.com/spesmilo/electrum.git .
        git submodule update --init
        python3 -m pip install --user -e .
        ./contrib/pull_locale
        cd $_tt/
        $(add_bin electrum $base_path/arc)
        installed_apps=$((installed_apps+1))
    ;;
    --get)
        run_electrum -o getconfig ${params[0]}
    ;;
    --set)
        run_electrum -o setconfig ${params[0]} ${params[1]}
    ;;
    *)
        run_electrum
    ;;
esac
