#!/bin/bash
electrum_path="$services_path/electrum"
sources="$services_path/electrum/sources"
electrum_data="$services_path/electrum/electrum_data"
send="$sources/run_electrum"


case "$command" in
    --daemon)
        $send daemon -d -D $electrum_data
        $send load_wallet -D $electrum_data
    ;;
    *)
        $send $@ --dir=$electrum_data
    ;;
esac