#!/bin/bash
root="$services_path/electrum"
sources="$root/ubuntu"
data="$root/data"
action="$command"
[[ ! -z $alter_cmd ]] && action="$alter_cmd"

function run_electrum {
    $sources/run_electrum $@ -D "$data"
}

case "$action" in
    --install)
        [[ $(which electrum) ]] && return
        $(rmkdir $root)
        echo "Registrando paquetes..."
        sudo apt-get install python3-pyqt5 libsecp256k1-0 python3-cryptography python3-setuptools python3-pip -y
        echo "Instalando Electrum"
        git clone --depth 1 https://github.com/arcaela/electrum.git $sources/
        $(add_bin electrum $base_path/arc)
        installed_apps=$((installed_apps+1))
    ;;
    --get)
        run_electrum -o getconfig ${params[0]}
    ;;
    --set)
        run_electrum -o setconfig ${params[0]} ${params[1]}
    ;;
    --start)
        run_electrum daemon -d
    ;;
    --stop)
        run_electrum stop
    ;;
    *)
        run_electrum
    ;;
esac