#!/bin/bash
installed_apps=0

function install_node {
    distro='linux-x64'
    version='v14.5.0'
    node_path="$services_path/nodejs"
    node_bash="$bash_path/nodejs.bash"
    delete $node_path
    delete $node_bash
    if [[ ! -f "$temp_path/node-$version-$distro.tar.xz" ]]; then
        echo "Descargando NodeJS $version"
        wget -P $temp_path/ https://nodejs.org/dist/$version/node-$version-$distro.tar.xz -q --show-progress
    fi
    if [[ -f "$temp_path/node-$version-$distro.tar.xz" ]]; then
        echo "Instalando NodeJS $version"
        sudo tar -xJf $temp_path/node-$version-$distro.tar.xz -C $services_path/
        sudo mv "$services_path/node-$version-$distro" $node_path/
        echo "Registrando recursos..."
        echo '#!/bin/bash
            PATH='$node_path'/bin:$PATH' >> $node_bash
        installed_apps=$((installed_apps+3))
    fi
}
function install_nodejs {
    install_node
}

function install_composer {
[[ $(which composer) ]] && return
composer_path="$services_path/composer"
composer_phar="$composer_path/composer.phar"
composer_bash="$bash_path/composer.bash"
if [[ $(which php) || $(in_array php ${params[@]}) || $(confirm "Composer requiere de PHP, ¿Continuar? Y") ]]; then
    [[ ! $(which php) ]] && install_php
    $(rmkdir $composer_path)
    $(delete $composer_bash)
    [[ -z $COMPOSER_HOME ]] && COMPOSER_HOME="$composer_path" && echo "export COMPOSER_HOME='$COMPOSER_HOME'" >> $composer_bash
    [[ -z $CGR_BASE_DIR ]] && CGR_BASE_DIR="$composer_path/global" && echo "export CGR_BASE_DIR='$CGR_BASE_DIR'" >> $composer_bash
    [[ -z $CGR_BIN_DIR ]] && CGR_BIN_DIR="$composer_path/vendor/bin" && echo "export CGR_BIN_DIR='$CGR_BIN_DIR'" >> $composer_bash
    echo $(parse_export $CGR_BIN_DIR) >> $composer_bash
    source $composer_bash
    if [[ ! -f $temp_path/composer.php ]]; then 
        echo "Descargando Composer"
        wget -O $temp_path/composer.php https://getcomposer.org/installer -q --show-progress
    fi
    echo "Instalando Composer..."
    php $temp_path/composer.php --install-dir=$composer_path/ --filename=composer.phar
    if [[ -f "$composer_phar" ]]; then
        $(add_bin composer $composer_phar)
       installed_apps=$((installed_apps+1))
    else
        echo "Error: No logramos instalar composer"
    fi
fi
}

function install_laravel {
    if [[ $(which composer) || $(in_array composer ${params[@]}) || $(confirm "Laravel requiere de Composer, ¿Continuar? Y") ]]; then
        [[ ! $(which composer) ]] && install_composer
        composer global require laravel/installer
        installed_apps=$((installed_apps+1))
    else
        echo "No podemos instalar Laravel sin composer"
    fi
}

function install_php {
    if [[ ! $(which php) ]]; then
        [[ ! $(grep -q "^deb .*ondrej/php" /etc/apt/sources.list /etc/apt/sources.list.d/*) ]] && sudo add-apt-repository ppa:ondrej/php -y
        sudo apt-get install software-properties-common php7.4 php-pear php7.4-curl php7.4-dev php7.4-gd php7.4-mbstring php7.4-zip php7.4-mysql php7.4-xml -y
        sudo apt-get update -y
    fi
    [[ $(which php) ]] && installed_apps=$((installed_apps+1)) || echo "No pudimos instalar PHP"
}

function install_apache2 {
    [[ $(command -v apache2) ]] && return
    sudo apt-get install software-properties-common apache2 -y
    sudo mkdir -p /etc/apache2/logs/
    sudo a2enmod rewrite
    systemctl restart apache2
    installed_apps=$((installed_apps+1))
}

function install_git {
    echo "Instalando git"
    [[ $(which git) ]] && return
    sudo apt-get install software-properties-common git -y
    echo "Git Instalado: $(which git)"
    installed_apps=$((installed_apps+1))
}


function install_electrum {
    [[ $(which electrum) ]] && return
    alter_cmd='--install'
    source $script_path/electrum
}


for require in ${params[@]}; do
    if typeset -f "install_$require" > /dev/null; then
        "install_$require"
    fi
done
echo "Se han instalado ($installed_apps) servicios."