#!/bin/bash
count=0

function install_nodejs {
    [[ $(which node) ]] && return
    version='v14.5.0'
    distro='linux-x64'
    node_path="$services_path/nodejs/$version"
    delete $node_path
    delete /usr/bin/npx
    delete /usr/bin/npm
    delete /usr/bin/node
    echo "Instalando NodeJS $version"
    if [[ ! -f "$temp_path/node-$version-$distro.tar.xz" ]]; then
        wget -P $temp_path/ https://nodejs.org/dist/$version/node-$version-$distro.tar.xz -q --show-progress
    fi
    mkdir -m 777 -p $(dirname $node_path)
    sudo tar -xJf "$temp_path/node-$version-$distro.tar.xz" -C $services_path
    sudo mv "$services_path/node-$version-$distro/" $node_path/
    echo "Registrando node"
    $(add_bin node $node_path/bin/node)
    echo "Registrando npm"
    $(add_bin npm $node_path/bin/npm)
    echo "Registrando npx"
    $(add_bin npx $node_path/bin/npx)
    count=$((count+1))
}

function install_composer {
[[ $(which composer) ]] && return
composer_path="$services_path/composer"
composer_phar="$composer_path/composer.phar"
composer_bash="/etc/bash_completion.d/arcaela_composer"
if [[ $(which php) || $(in_array php ${params[@]}) || $(confirm "Composer requiere de PHP, ¿Continuar? Y") ]]; then
    [[ ! $(which php) ]] && install_php
    echo "Instalando Composer"
    if [[ -f $composer_bash ]]; then
        source $composer_bash
    else
        COMPOSER_HOME="$composer_path"           
        CGR_BASE_DIR="$composer_path/global"     
        CGR_BIN_DIR="$composer_path/vendor/bin"
    echo "export CGR_BIN_DIR=$CGR_BIN_DIR
export CGR_BASE_DIR=$CGR_BASE_DIR
export COMPOSER_HOME=$COMPOSER_HOME
export PATH=$PATH:$composer_path/vendor/bin" >> $composer_bash
    sudo chmod -R 777 $composer_bash
    fi
    if [[ ! -f "$composer_phar" ]]; then
        mkdir -m 777 -p $composer_path
        [[ ! -f $temp_path/composer.php ]] && wget -O $temp_path/composer.php https://getcomposer.org/installer -q --show-progress
        php $temp_path/composer.php --install-dir=$composer_path/ --filename=composer.phar
        sudo chmod -R 777 $composer_path
    fi
    if [[ -f "$composer_phar" ]]; then
        sudo rm /usr/bin/composer
        $(add_bin composer $composer_phar)
       count=$((count+1))
    else
        echo "Error: No logramos instalar composer"
    fi
fi
}

function install_laravel {
    if [[ $(which composer) || $(in_array composer ${params[@]}) || $(confirm "Laravel requiere de Composer, ¿Continuar? Y") ]]; then
        [[ ! $(which composer) ]] && install_composer
        composer global require laravel/installer
    else
        echo "No podemos instalar Laravel sin composer"
    fi
}

function install_php {
    if [[ ! $(which php) ]]; then
        [[ ! $(grep -q "^deb .*ondrej/php" /etc/apt/sources.list /etc/apt/sources.list.d/*) ]] && sudo add-apt-repository ppa:ondrej/php -y
        sudo apt-get install software-properties-common php7.4 php-pear php7.4-curl php7.4-dev php7.4-gd php7.4-mbstring php7.4-zip php7.4-mysql php7.4-xml -qq
        sudo apt-get upgrade -qq
    fi
    [[ $(which php) ]] && echo "PHP se ha instalado "$(php -v) || echo "No pudimos instalar PHP"
}

function install_apache2 {
    [[ $(which a2enmod) ]] && return
    sudo apt-get install software-properties-common apache2 -qq
    sudo apt-get upgrade -qq
    sudo mkdir -p /etc/apache2/logs/
    sudo a2enmod rewrite
    systemctl restart apache2
}

function install_git {
    echo "Instalando git"
    [[ $(which git) ]] && return
    sudo apt-get install software-properties-common git -qq
    sudo apt-get upgrade -qq
    echo "Git Instalado: $(which git)"
}


function install_electrum {
    [[ $(which electrum) ]] && return
    echo "Instalando Electrum"
    electrum_path="$services_path/electrum"
    if [[ ! -f "$temp_path/electrum.zip" ]]; then
        echo "Descargando Electrum..."
        wget -O $temp_path/electrum.zip https://github.com/spesmilo/electrum/archive/master.zip -q --show-progress
    fi
    echo "Registrando paquetes..."
    delete "$services_path/electrum/"
    unzip -qq $temp_path/electrum.zip -d $temp_path/
    mv -f "$temp_path/electrum-master/" "$services_path/electrum/"
    $(add_bin electrum "$base_path/arc")
}






for require in ${params[@]}; do
    if typeset -f "install_$require" > /dev/null; then
        "install_$require"
    fi
done
# echo "Se han instalado ($count) servicios."