#!/bin/bash
nodejs_home="$bin_path/nodejs"

VERSION="v14.5.0"
DISTRO="linux-x64"
if [[ ! -f "$temp_path/nodejs.tar.xz" ]]; then
    wget -O $temp_path/nodejs.tar.xz https://nodejs.org/dist/$VERSION/node-$VERSION-$DISTRO.tar.xz -q --show-progress
fi
sudo tar -xJvf $temp_path/nodejs.tar.xz -C $bin_path
sudo mv "$bin_path/node-$VERSION-$DISTRO/" $bin_path/nodejs/
link $nodejs_home/bin/node /usr/bin/node
link $nodejs_home/bin/npm /usr/bin/npm
link $nodejs_home/bin/npx /usr/bin/npx