#!/bin/bash
# Instalación de NodeJS
node_path="$package_path/nodejs"
nodeVersion="v14.5.0"
nodeDistro="linux-x64"

delete $node_path
delete $bin_path/node
delete $bin_path/npm
delete $bin_path/npx
if [[ ! -f "$temp_path/nodejs.tar.xz" ]]; then
    wget -O $temp_path/nodejs.tar.xz https://nodejs.org/dist/$nodeVersion/node-$nodeVersion-$nodeDistro.tar.xz -q --show-progress
fi
sudo tar -xJf $temp_path/nodejs.tar.xz -C $package_path
sudo mv "$package_path/node-$nodeVersion-$nodeDistro/" "$node_path/"
link $node_path/bin/node $bin_path/node
link $node_path/bin/npm $bin_path/npm
link $node_path/bin/npx $bin_path/npx
# Fin de NodeJS